### ISSUE TITLE
how to export step from Obj?

### ISSUE THREAD

**Issue by selvakarna** [LeSuisse/obj-3d-to-array#1]
how to export step from Obj?

**Comment by LeSuisse** [comment]
Hi,

I'm not quite sure to understand the question, can you please explain a bit more what you are trying to achieve?

Anyway, I should have archived this repo a while ago. It was more of an ugly hack than anything else.

**Comment by selvakarna** [comment]
HI, @LeSuisse ,

I am asking, How to write 3D obj file into IGES (or) STEP CAD Model? can you share sample code?

**Comment by LeSuisse** [comment]
I have absolutely no clue about that sorry.
